### ISSUE TITLE
disableOnInvalid: true doesn't disable the Submit button

### ISSUE THREAD

**Issue by sachitsac** [formio/angular-formio#130]
Hi,

I have embedded a formio form in a angular 4 application generated using angular-cli (1.x.x) using angular-formio ( upgraded from ng2-form ) and my form configuration has disableOnInvalid: true but upon rendering the form, the submit button isn't disabled. Even when invalid fields errors are triggered, the form isn't being disabled. Let me know if you need more info.

Angular form io version used: 0.13.0

Form component included in html like this:

```
<formio (submit)="onComplete($event)" [options]="options" [src]="url"></formio>
```

Here is the form:
```
{
	"_id": "xxx",
	"machineName": "xxx",
	"modified": "2017-08-22T06:39:13.153Z",
	"title": "Add User",
	"display": "form",
	"name": "addUser",
	"path": "reg",
	"project": "xxx",
	"created": "2017-08-22T02:41:24.987Z",
	"components": [{
		"description": "",
		"properties": {
			"": ""
		},
		"tags": [],
		"type": "textfield",
		"conditional": {
			"eq": "",
			"when": null,
			"show": ""
		},
		"validate": {
			"customPrivate": false,
			"custom": "",
			"pattern": "",
			"maxLength": "",
			"minLength": 2,
			"required": true
		},
		"clearOnHide": true,
		"hidden": false,
		"persistent": true,
		"unique": false,
		"protected": false,
		"defaultValue": "",
		"multiple": false,
		"suffix": "",
		"prefix": "",
		"placeholder": "Enter Firstname...",
		"key": "firstName",
		"label": "First Name:",
		"inputMask": "",
		"inputType": "text",
		"tableView": true,
		"input": true
	}, {
		"properties": {
			"": ""
		},
		"tags": [],
		"type": "textfield",
		"conditional": {
			"eq": "",
			"when": null,
			"show": ""
		},
		"validate": {
			"customPrivate": false,
			"custom": "",
			"pattern": "",
			"maxLength": "",
			"minLength": 2,
			"required": true
		},
		"clearOnHide": true,
		"hidden": false,
		"persistent": true,
		"unique": false,
		"protected": false,
		"defaultValue": "",
		"multiple": false,
		"suffix": "",
		"prefix": "",
		"placeholder": "Enter Last name...",
		"key": "lastName",
		"label": "Last Name",
		"inputMask": "",
		"inputType": "text",
		"tableView": true,
		"input": true
	}, {
		"validate": {
			"required": true
		},
		"properties": {
			"": ""
		},
		"conditional": {
			"eq": "",
			"when": null,
			"show": ""
		},
		"tags": [],
		"type": "email",
		"kickbox": {
			"enabled": false
		},
		"clearOnHide": true,
		"hidden": false,
		"persistent": true,
		"unique": false,
		"protected": false,
		"defaultValue": "",
		"suffix": "",
		"prefix": "",
		"placeholder": "Enter Email Address ...",
		"key": "email",
		"label": "Email Address",
		"inputType": "email",
		"tableView": true,
		"input": true
	}, {
		"validate": {
			"minLength": 8,
			"required": true
		},
		"tabindex": "",
		"properties": {
			"": ""
		},
		"conditional": {
			"eq": "",
			"when": null,
			"show": ""
		},
		"tags": [],
		"source": "xxx",
		"lockKey": true,
		"type": "password",
		"clearOnHide": true,
		"hidden": false,
		"persistent": true,
		"protected": true,
		"suffix": "",
		"prefix": "",
		"placeholder": "Enter password...",
		"key": "password",
		"label": "Password",
		"inputType": "password",
		"tableView": false,
		"input": true
	}, {
		"lockKey": true,
		"properties": {
			"": ""
		},
		"conditional": {
			"eq": "",
			"when": "",
			"show": ""
		},
		"tags": [],
		"type": "button",
		"theme": "primary",
		"disableOnInvalid": true,
		"action": "submit",
		"block": false,
		"rightIcon": "",
		"leftIcon": "",
		"size": "md",
		"key": "submit",
		"tableView": false,
		"label": "Submit",
		"input": true
	}],
	"owner": "xxx",
	"submissionAccess": [{
		"type": "create_all",
		"roles": []
	}, {
		"type": "read_all",
		"roles": []
	}, {
		"type": "update_all",
		"roles": []
	}, {
		"type": "delete_all",
		"roles": []
	}, {
		"type": "create_own",
		"roles": []
	}, {
		"type": "read_own",
		"roles": []
	}, {
		"type": "update_own",
		"roles": []
	}, {
		"type": "delete_own",
		"roles": []
	}, {
		"type": "team_read",
		"roles": []
	}, {
		"type": "team_write",
		"roles": []
	}, {
		"type": "team_admin",
		"roles": []
	}],
	"access": [{
		"type": "create_all",
		"roles": []
	}, {
		"type": "read_all",
		"roles": ["xxx", "xxx", "xxx"]
	}, {
		"type": "update_all",
		"roles": []
	}, {
		"type": "delete_all",
		"roles": []
	}, {
		"type": "create_own",
		"roles": []
	}, {
		"type": "read_own",
		"roles": []
	}, {
		"type": "update_own",
		"roles": []
	}, {
		"type": "delete_own",
		"roles": []
	}, {
		"type": "team_read",
		"roles": []
	}, {
		"type": "team_write",
		"roles": []
	}, {
		"type": "team_admin",
		"roles": []
	}],
	"tags": [],
	"type": "form"
}
` ``

**Comment by dannymcpherson** [comment]
Same here, just using vanilla Javascript SDK.  Submit button isn't hidden as expected.

**Comment by kacperdev** [comment]
Hi,
I have to admit that is really great library, but it has some flaws :( 
Are you going to fix that bug? Because it's still not working properly.

**Comment by travist** [comment]
Yep, we will include this in our planning for the week. We have quite a bit of items we are currently developing so it may be a couple of weeks before resolution (unless we determine this is critical). In the meantime, you can see all of the source code for this issue @ https://github.com/formio/formio.js, and more specifically, the logic that controls the disableOnInvalid logic can be found in the Button component @ https://github.com/formio/formio.js/blob/master/src/components/button/Button.js#L193

**Comment by pravin-mamdge** [comment]
Hi @travist, we saw this issue after upgrading to the latest version. With the following versions, we don't see this issue. 
"angular-formio": "1.6.4",
"formiojs": "2.24.5"

Are you planning to schedule this issue in the next release?

**Comment by travist** [comment]
Your formiojs version is really old. I am pretty sure we have fixed this problem since then. Try upgrading formiojs to the 3.16.3 version.

**Comment by pravin-mamdge** [comment]
Thanks, @travist. But after updating the formiojs to the latest version 3.16.3 submit button is not getting disabled. I have updated the fiddle where I have set "disableOnInvalid" property to true for the submit button and the form has one mandatory field, but after running the fiddle the Submit button is enabled. 
http://jsfiddle.net/pmamdge/9v3Lcdw2/4/

**Comment by travist** [comment]
Yeah, this is a bug. We will take a look.

**Comment by pravin-mamdge** [comment]
Thank You.

**Comment by pravin-mamdge** [comment]
@travist Is there any ETA on this issue?

There is one workaround available i.e. We can catch change event on form and update the state of the submit button explicitly. We get the state of submit button using form.formio.isValid(submission, true) but with the above workaround, we see a flickering issue when any field in form gets updated.

**Comment by randallknutson** [comment]
We're still working on this item. Were hoping to get this fixed here shortly.

**Comment by pravin-mamdge** [comment]
Hi @randallknutson. Is it possible for you to provide any ETA on this issue?

**Comment by wag110894** [comment]
Hello,
We estimate that this will be fixed by the end of next week. 

We will keep you posted.

Thank you for your patience in regards to this issue.

**Comment by abhishek1681993** [comment]
Hi @randallknutson,
I am also facing the same issue that, submit button is not getting disabled after entering an invalid value in the form. Is there any workaround or solution to this problem.

**Comment by travist** [comment]
This is still in our backlog. If anyone needs to expedite (for a fee) let us know and we can get a developer on it this week. Otherwise, it will just get done once a developers gets through other expedited items.

**Comment by vikram-shityalkar** [comment]
Thank you @travist.

We are stuck too on this but currently, we don’t have the funding allocated to fund one of the developers, but we would be happy to provide a resource to help if we got a few pointers. Either way, getting an estimated ETA would be much appreciated.

**Comment by travist** [comment]
The only pointers I can provide is where in the code this is handled. It would be up to the person debugging this to set some breakpoints to determine why this gets in a bad state.

The code is going to be in the "node_modules/formiojs" library at this point.

https://github.com/formio/formio.js/blob/master/src/components/button/Button.js#L191

For some reason, this is not disabling correctly. Not sure why.

**Comment by vikram-shityalkar** [comment]
Thank You @travist 

We will try to debug and post the findings here.

**Comment by ASmeha** [comment]
I tried to debug the issue and these are my findings, hope they help: 

- [this.shouldDisable](https://github.com/formio/formio.js/blob/master/src/components/base/Base.js#L509) of (Base) is always false because this.component.disabled is always false

- Because of 1) , when setting [disabled to true](https://github.com/formio/formio.js/blob/master/src/components/button/Button.js#L193) , the [setter](https://github.com/formio/formio.js/blob/master/src/components/button/Button.js#L60) always returns undefined and doesn't proceed to add the class to disable the button 

any suggestions on how to fix it? when to set the 'disabled' attr of 'component' and how?

**Comment by wag110894** [comment]
Hello All,

Thank you for your patience regarding this issue. This has been resolved in our latest 4x renderer.

Please let us know if you have any further questions or concerns.

**Comment by franke-mc** [comment]
Hello @wag110894,
could you please elaborate a bit on the current state of 3.x and 4.x versions of formio? In [issue 296](https://github.com/formio/angular-formio/issues/296#issuecomment-499267511) the on June 5th, it had been stated that 3.x was still the "current" way. Has this changed? Has focus switched to 4.x? Which version do you currently propose for use-cases where a robust library is needed in production? Are bugs in 3.x going to be fixed going forward? Which version has fewer annoying bugs in practice which could be showstoppers in production? Does this differ between angular and react frameworks? What is the plan for the coming weeks & months?
Any details are much appreciated; it will make contributing back easier, too...

**Comment by travist** [comment]
@franke-mc we are heavily investing into solidifying 4.x. It is still not ready for production quite yet, but is quickly getting there. We do have a number of customers using it in production, but they are confined to a few controls / use cases that have proven to be solid. We are expecting to be at a production ready point by the end of September.

As for 3.x. This is our current production renderer and we will still fix critical issues with that renderer. This particular item is a bug, but falls behind our development teams current initiatives working with customer requirements, so I am afraid it will most likely just sit here until one of the following occurs.

 1.) Someone comes alone and pays to expedite the resolution of this which would throw the priority of this item above our current customer developments, meaning someone on the Form.io dev team will be assigned to this issue.

 2.) 4.x moves into a stable point, which since it uses a completely different rendering issue, this issue may not exist in that renderer. If that is the case, then we will at that moment recommend people move onto this renderer since it is compatible with JSON from 3.x.

Hope this helps clarify things.

**Comment by sandeepspace** [comment]
Hi @sachitsac, this issue can be done by forming a custom id on <formio> tag & change event where you want to display form builder fields. 
I was also facing the same issue and with extra e014 text which was appended into submit button text.
like--  [**Submit e014 (If Form is invalid)**](url)
Step 1: <formio id="formio" [form]="formBuilderData" (submit)="fbSubmit($event)" (change)="isFbChanges($event)">
            </formio>
Step 2: After component initialization check form builder's any field is required or not. 
Step 3: By Loop --> check 'validate' key is present & inside that required is true.(In particular FB field)
Step 4: Get Formio Submit Button from DOM by this code and disable button based on validation
            document.getElementById('formio').getElementsByTagName('button')[0].disabled=true/false;
Step 5: Listen change event -->> isFbChanges(event: any) {
    if (event && 'type' in event && event.type == 'change') {  // this line will prevent on mouse change event or any changes done 
                                                                                             //by hovering mouse on Screen 
      return;
    }
    if (event && event.changed && event.changed != undefined && event.isValid) {
      document.getElementById('formio').getElementsByTagName('button')[0].disabled=false;
    } else {
      document.getElementById('formio').getElementsByTagName('button')[0].disabled=true;
    }
  }
Step 6: Final Submission --> fbSubmit(event: any){//do something}

@travist My formio version is "angular-formio": "^3.20.0".
I hope this will help.
Thanks
