### ISSUE TITLE
Date/Time Component Rendering Issue In Prod Build

### ISSUE THREAD

**Issue by cfsilence** [formio/angular-formio#155]
I'm seeing issues with the Data Grid component in a prod build (`ng build --prod`) on 1.8.0.

The component renders properly in dev mode (`npm start`) locally, but on the server the fields are all being displayed as read only and it looks like the 'flatpickr' CSS isn't being included in the build because a gigantic arrow icon with the classes `flatpickr-calendar hasTime animate` is shown at the bottom of the page and there aren't any flatpickr related styles applied to it.

Let me know if you need any more info on this issue, thanks!

**Comment by cfsilence** [comment]
Dev version:

![image](https://user-images.githubusercontent.com/462773/35166221-1e1c3a76-fd1f-11e7-872c-d887caa222c0.png)

Prod version:

![image](https://user-images.githubusercontent.com/462773/35166235-2a5b2aea-fd1f-11e7-8c9b-ca585c9b1c01.png)

Gigantic SVG arrow at bottom of page:

![image](https://user-images.githubusercontent.com/462773/35166255-3b53c5dc-fd1f-11e7-8f97-fcd1c277c8c3.png)

**Comment by cfsilence** [comment]
In looking at it, only the date pickers are readonly I guess.

**Comment by cfsilence** [comment]
Updated the title, the issue is related to the date/time component, not the data grid.

**Comment by cfsilence** [comment]
I believe the issue is here:

https://github.com/formio/angular-formio/blob/master/src/formio.component.ts#L39

As explained here:

https://github.com/angular/angular-cli/issues/6422

Can you switch to using:

`styleUrls: ['formio.component.scss']`

instead of inlining the styles?

**Comment by travist** [comment]
I looked into doing this, but it didn't seem to work with a package build. I may experiment with some more things but will try to get this resolved ASAP.

**Comment by cfsilence** [comment]
I'm trying to include that css directly into my build to bypass the error, but our Jenkins server is having issues at the moment so I can't confirm that it works just yet.  I'll let you know if it does.

**Comment by travist** [comment]
What I may have to do is resolve this on the renderer side @ https://github.com/formio/formio.js where it just includes the css directly into the DOM. Let me know if you have any luck on your end and I may go that route.

**Comment by cfsilence** [comment]
OK, got my build deployed and confirmed that including the CSS directly into my stylesheet via:

`@import '../node_modules/angular-formio/formio.component';`

Resolved this issue for me.  It's not the most elegant solution, but it works so I'm happy.

**Comment by astacy2** [comment]
I am also having the same issue but adding the @import directly to my CSS didn't resolve the issue. Currently using version 1.17.0.

Thanks.

**Comment by travist** [comment]
This should be fixed in latest version. Please verify if it is not.

**Comment by bolatk** [comment]
@travist the issue is not fixed. I tested with `angular-formio` 3.10.2.
