### ISSUE TITLE
Datetime component is not removed from <body>

### ISSUE THREAD

**Issue by jftsaraiva** [formio/angular-formio#223]
When we have one form with one or more datetime component each time that the form is rendered it adds one more ```<div class="flatpickr-calendar animate" tabindex="-1">...</div>``` to `<body>`

After some time of use of the application we can have dozens (or even hundreds) of dummy divs.

![image](https://user-images.githubusercontent.com/2278476/48303375-4202ae00-e501-11e8-8115-a5d2d2f8a2e7.png)

This could be easily replicated in [https://formio.github.io/angular-demo/manager](https://formio.github.io/angular-demo/manager)

Is there anything we could on ngOnDestroy to release that when we navigate to out of the form?

**Comment by wag110894** [comment]
Hello João,
Thanks for reaching out!
We have added this to our backlog. We also accept pull requests if you are interested in contributing this fix. 
 
Thanks!

**Comment by javo9space** [comment]
Any updates on this issue?

**Comment by Javo-blip** [comment]
Any updates on this issue? Still experiencing this in react-formio as well

**Comment by jhen1422** [comment]
@Javo-blip
This issue has been resolved in the latest version of 4x.

**Comment by Javo-blip** [comment]
I seem to be still experiencing this issue on formio-react, should I open a new issue in that repo?

**Comment by jhen1422** [comment]
@Javo-blip Yes, please reopen a new ticket in the React issue  board.

Thanks!
